### ISSUE TITLE
DeprecationWarning / UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by jkleininger** [vHanda/google-keep-exporter#19]
As others have reported, I'm getting

`Converted 0 notes`

when running against the takeout zip file.  So, following the earlier suggestion, I'm attempting to run against the extracted directory: ./Takeout/Keep

When doing so, I run into the following error:

`22:19:02 [~/keep] $ ./google-keep-exporter-linux in/Takeout/Keep/ out/
(node:88669) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(node:88669) UnhandledPromiseRejectionWarning: Error: ENAMETOOLONG: name too long, open 'out//TIL-that-no-matter-the-language-we-all-exchange-information-at-39-bitssecond-suggesting-a-biological-limit-Languages-that-are-lower-information-density-are-spoken-fast-Spanish--Japanese-while-denser-languages-are-spoken-more-slowly-Thai-Vietnamese-Chinese.md'
    at Object.fs.openSync (fs.js:579:3)
    at Object.fs.openSync (pkg/prelude/bootstrap.js:483:32)
    at Object.fs.writeFileSync (fs.js:1309:33)
    at output.forEach.out (/snapshot/google-keep-exporter/dist/main.js:0:0)
    at Array.forEach (<anonymous>)
    at convertNote (/snapshot/google-keep-exporter/dist/main.js:0:0)
    at files.forEach.filePath (/snapshot/google-keep-exporter/dist/main.js:0:0)
    at Array.forEach (<anonymous>)
    at convertNotes (/snapshot/google-keep-exporter/dist/main.js:0:0)
    at /snapshot/google-keep-exporter/dist/main.js:0:0
(node:88669) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:88669) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
`

I've tried removing the referenced files (html and json) and the utility indeed appears to proceed until it runs into another "name too long" error on another note.  Is it possible to catch this error and truncate the filename?

**Comment by jkleininger** [comment]
Just noticed this looks to be a duplicate of #9
